# Source code language
language: ruby

# The compiler version
rvm:
- 2.1

# Use Bundler to install gems
install: bundle install --jobs=3 --retry=3

# Use Jekyll to build site & perform sanity check
script: jekyll build && htmlproof ./_site

env:
  global:
  # speeds up installation of html-proofer
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
